In [1]:
import numpy as np



In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a+2

array([3, 4, 5, 6])

In [4]:
a*2

array([2, 4, 6, 8])

In [5]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [6]:
a+=2

In [7]:
print(a)

[3 4 5 6]


In [8]:
#Squares
a = np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [9]:
#sine of values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [10]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [13]:
b = np.array([2,7,8,4])
a+b



array([ 3,  9, 11,  8])

In [14]:
a*b

array([ 2, 14, 24, 16])

In [15]:
a = np.ones((2,3))

In [16]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
b = np.full((3,2), 2)

In [18]:
print(b)


[[2 2]
 [2 2]
 [2 2]]


In [19]:
#Matrix multiplication

np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [20]:
c = np.identity(3)

In [21]:
#determinant
np.linalg.det(c)

1.0

In [23]:
np.linalg.det(np.matmul(a,b))

0.0

In [25]:
stats = np.array([[1,2,3],[4,5,6]]) 
#min
np.min(stats)

1

In [26]:
#max
np.max(stats)

6

In [27]:
np.min(stats, axis=0)

array([1, 2, 3])

In [28]:
np.max(stats, axis=1)

array([3, 6])

In [29]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [30]:
#Reshaping
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [33]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
#Vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])
      

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [35]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h1


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
h2

array([[0., 0.],
       [0., 0.]])

In [39]:
np.hstack((h2,h1))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])