In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# get dimesion
a.ndim

1

In [5]:
#get shape
b.shape

(2, 3)

In [6]:
#get type
a.dtype


dtype('int64')

In [7]:
#to specify memory of an array

c = np.array([2, 3, 4], dtype='int16')
c.dtype



dtype('int16')

In [8]:
#get size
a.itemsize

8

In [9]:
c.itemsize

2

In [10]:
#total size
a.size*a.itemsize


24

In [11]:
b.itemsize

8

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.shape

(2, 7)

In [16]:
#get a specific element
a[1, 5]

13

In [17]:
a[1, -2]

13

In [18]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#get a specific column
a[:, 2]


array([ 3, 10])

In [22]:
a[:, 3]

array([ 4, 11])

In [23]:
#[start:end:stepsize]

a[0, 1:5:2]

array([2, 4])

In [24]:
a[0, 1:6:2]

array([2, 4, 6])

In [25]:
a[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [26]:
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
#change element

a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
a[:, 3] = [1, 2]
print(a)

[[ 1  2  1  1  5  6  7]
 [ 8  9  2  2 12 20 14]]


In [31]:
#3D

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
#specific element

b[0,1,1]

4

In [33]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [34]:
#replace
b[:,1,:] = [[9,9],[8,8]]

In [35]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
