In [6]:
import numpy as np

filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)


[[ 2.  4. 55.  6.  7.  8.  9. 23. 54. 57. 43. 45.]
 [57. 89.  3.  5.  7.  0.  1.  5.  7. 89. 24. 78.]
 [ 4.  4.  7.  9. 60. 24.  1.  2.  3.  4.  5.  6.]]


In [10]:
#to specify type
filedata = filedata.astype('int32')
print(filedata)

[[ 2  4 55  6  7  8  9 23 54 57 43 45]
 [57 89  3  5  7  0  1  5  7 89 24 78]
 [ 4  4  7  9 60 24  1  2  3  4  5  6]]


In [12]:
#Boolean masking and Advanced indexing

#Condition for all elements
filedata > 50

array([[False, False,  True, False, False, False, False, False,  True,
         True, False, False],
       [ True,  True, False, False, False, False, False, False, False,
         True, False,  True],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False]])

In [13]:
#Finding index for condition
filedata[filedata > 50]

array([55, 54, 57, 57, 89, 89, 78, 60], dtype=int32)

In [16]:
#You can index with alist in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [18]:
#axis=0 means columns
#axis=1 means rows

#Coditon for columns(For atleast one element)
np.any(filedata > 50, axis = 0)


array([ True,  True,  True, False,  True, False, False, False,  True,
        True, False,  True])

In [19]:
#Condition for all elements
np.all(filedata > 50, axis = 0)


array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [21]:
((filedata > 50) & (filedata < 100))

array([[False, False,  True, False, False, False, False, False,  True,
         True, False, False],
       [ True,  True, False, False, False, False, False, False, False,
         True, False,  True],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False]])

In [22]:
#Negation of previous condition

(~(filedata > 50) & (filedata < 100))

array([[ True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True]])

In [23]:
#indexing in numpy is differnt**

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [24]:
#Indexing(index:actual_number)
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [25]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [26]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
# 3: means from 3 to last column
#We can also use 3:5
