In [3]:
#all zeros matrix
import numpy as np

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,3,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [8]:
#all ones matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [9]:
#we can also add dtype
np.ones((3,4,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [10]:
#any other number
np.full((2,2),15)

array([[15, 15],
       [15, 15]])

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [12]:
#full_like(Same dimensions as a)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [13]:
# random decimal nums
np.random.rand(4,3)

array([[0.25179096, 0.43002214, 0.60083127],
       [0.49533271, 0.58022174, 0.02274799],
       [0.14674377, 0.34757931, 0.53728252],
       [0.81942878, 0.5872811 , 0.84587549]])

In [14]:
np.random.random_sample(a.shape)

array([[0.78034898, 0.80344597, 0.68510269, 0.16430929, 0.1539096 ,
        0.69800859, 0.64270807],
       [0.38135094, 0.97456711, 0.0417817 , 0.06898215, 0.74053891,
        0.81823403, 0.12525445]])

In [19]:
#random int values
#from 0 to 7
np.random.randint(7,size=(3,3))

array([[4, 2, 6],
       [3, 2, 1],
       [0, 5, 3]])

In [21]:
np.random.randint(1,size=(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
#from -4 to 8
np.random.randint(-4, 8, size=(3,3))


array([[ 3,  0, -3],
       [-4, -4,  2],
       [ 1,  2,  6]])

In [23]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)

In [25]:
print(r1)

[1 1 1 2 2 2 3 3 3]


In [27]:
#making it 2D array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
mat = np.ones((5,5))
print(mat)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
z[1, 1] = 9

In [37]:
mat[1:-1, 1:-1] = z

print(mat)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
#be careful while copying arrays

a= np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [39]:
print(a)

[100   2   3]


In [40]:
#but a[0] shouldnt b zero
#so use copy fn

a= np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)



[100   2   3]


In [41]:
print(a)

[1 2 3]
