In [1]:
import pandas as pd

pd.__version__

'1.4.4'

In [2]:
a = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [4]:
a.values

array([2, 3, 4, 5])

In [5]:
type(a.values)

numpy.ndarray

In [6]:
type(a)

pandas.core.series.Series

In [7]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
#Like dictionary
a['a']

2

In [9]:
a[0]

2

In [10]:
a['a':'c']

a    2
b    3
c    4
dtype: int64

In [11]:
a[0:3]

a    2
b    3
c    4
dtype: int64

In [34]:
grad_dict = {'A':9, 'B':8, 'C':7, 'D':6}
grad = pd.Series(grad_dict, dtype='float64')

In [35]:
print(grad)

A    9.0
B    8.0
C    7.0
D    6.0
dtype: float64


In [33]:
marks_dict = {'A':90, 'B':80, 'C':70, 'D':60}
marks = pd.Series(marks_dict, dtype = 'float64')
print(marks)

A    90.0
B    80.0
C    70.0
D    60.0
dtype: float64


In [22]:
grad.values

array([9, 8, 7, 6])

In [23]:
marks.values

array([90, 80, 70, 60])

In [17]:
marks['A']

90

In [18]:
marks[0:2]

A    90
B    80
dtype: int64

In [36]:
d = pd.DataFrame({'Marks':marks, 'Grade':grad})
d

Marks  Grade
A   90.0    9.0
B   80.0    8.0
C   70.0    7.0
D   60.0    6.0

In [31]:
#Transpose
d.T

A     B     C     D
Marks  90.0  80.0  70.0  60.0
Grade   9.0   8.0   7.0   6.0

In [37]:
d.values

array([[90.,  9.],
       [80.,  8.],
       [70.,  7.],
       [60.,  6.]])

In [38]:
#Accesing values
d.values[2,0]

70.0

In [39]:
d.columns

Index(['Marks', 'Grade'], dtype='object')

In [40]:
d['Scaled Marks'] = 100*(d['Marks']/90)
d

Marks  Grade  Scaled Marks
A   90.0    9.0    100.000000
B   80.0    8.0     88.888889
C   70.0    7.0     77.777778
D   60.0    6.0     66.666667

In [41]:
d['Marks']

A    90.0
B    80.0
C    70.0
D    60.0
Name: Marks, dtype: float64

In [42]:
del d['Scaled Marks']
d

Marks  Grade
A   90.0    9.0
B   80.0    8.0
C   70.0    7.0
D   60.0    6.0

In [43]:
g = d[d['Marks'] > 70]
g

Marks  Grade
A   90.0    9.0
B   80.0    8.0

In [69]:
#Missing values(NaN)

f = pd.DataFrame([{'a':1,'b':2,'c':4}, {'b':3, 'c':4}])
f


a  b  c
0  1.0  2  4
1  NaN  3  4

In [70]:
#Fill NaN(empty) values with a fixed value

f = f.fillna(0)
f



a  b  c
0  1.0  2  4
1  0.0  3  4

In [73]:
f = pd.DataFrame([{'a':1,'b':2,'c':4}, {'b':3, 'c':4}])
f.dropna()


a  b  c
0  1.0  2  4